services:
  handbrake-webui:
    image: ray5378/handbrake-webui-fnapp:${TRIM_APPVER:-latest}
    container_name: handbrake-webui
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${TRIM_PKGVAR}/config:/config
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PORT=${TRIM_SERVICE_PORT:-52389}
      - CONFIG_DIR=/config
      - NODE_ENV=production
      - TRIN_DATA_ACCESSIBLE_PATHS=${TRIM_DATA_ACCESSIBLE_PATHS:-}
      - TRIN_APP_STATUS=${TRIM_APP_STATUS:-}