#!/bin/bash

IMAGE_NAME="ray5378/handbrake-webui-fnapp:latest"

load_docker_image() {
  docker pull "${IMAGE_NAME}" || {
    echo "Failed to pull image ${IMAGE_NAME}" >&2
    return 1
  }
}

load_docker_image
exit 0
